typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#b8bb26'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#fb4934'

typeset -g POWERLEVEL9K_DIR_FOREGROUND='#d79922'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#d79921'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#d79921'
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_LOCK_ICON=''

typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND='#cc241d'
typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_VISUAL_IDENTIFIER_COLOR='#cc241d'

typeset -g POWERLEVEL9K_DIR_CLASSES=()

### vcs: git status ###
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '

# Disable the default Git status formatting.
typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=false

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#a89984'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#458588'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#458588'
typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND='#928374'

typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR='#d3869b' #76
typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR='#928374' #244
typeset -g POWERLEVEL9K_VCS_PREFIX='%fon '

typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNTRACKEDFORMAT_FOREGROUND='#fb4934'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNSTAGEDFORMAT_FOREGROUND='#fe8019'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED0MODIFIED}_STAGEDFORMAT_FOREGROUND='#b8bb26'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_INCOMING_CHANGESFORMAT_FOREGROUND='#8ec07c'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_OUTGOING_CHANGESFORMAT_FOREGROUND='#83a598'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASHFORMAT_FOREGROUND='#ebdbb2'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTIONFORMAT_FOREGROUND=001
typeset -g POWERLEVEL9K_VCS_LOADING_ACTIONFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_LOADING_FOREGROUND

# typeset -g POWERLEVEL9K_VCS_GIT_ICON=''
# typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
# typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
# typeset -g POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''
typeset -g POWERLEVEL9K_VCS_GIT_ICON=''
typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
typeset -g POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''
# typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='  '
# typeset -g POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON='  '
typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='C:' #' '
typeset -g POWERLEVEL9K_VCS_STAGED_ICON='S:' #' '
typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='M:' #' '
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?:' #'✩ '
typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'
typeset -g POWERLEVEL9K_VCS_STASH_ICON='*'
typeset -g POWERLEVEL9K_VCS_TAG_ICON=' '

### status: exit code of last command ###
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#b8bb26'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#cc241d'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#cc241d'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#cc241d'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#cc241d'

### command_execution_time: duration of last command ###
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#a89984'

### background_jobs: presence of background jobs ###
# Don't show the number of background jobs.
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
# Background jobs color.
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=none # ?? works
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=70
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_COLOR=2
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON='⇶'

  ### asdf
  # Tip:  Override this parameter for ${TOOL} with POWERLEVEL9K_ASDF_${TOOL}_FOREGROUND.
typeset -g POWERLEVEL9K_ASDF_FOREGROUND=66

### context: user@hostname ###
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#ea6962'
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,REMOTE_SUDO,REMOTE,SUDO}_FOREGROUND='#e78a4e'
typeset -g POWERLEVEL9K_CONTEXT_PREFIX='%fwith '
typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
