[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
# orange = "#fe8019"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.dim]
black = "#282828"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
# orange = "#af3a03"
red = "#9d0006"
white = "#bdae93"
yellow = "#b57614"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
# orange = "#d65d0e"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#202020"
foreground = "#ebdbb2"
