require("colorizer").setup()
require("Comment").setup()

require("nelavim.lspinstall")
require("nelavim.lualine")
require("nelavim.telescope")
require("nelavim.nvim-tree")
require("nelavim.treesitter")
require("nelavim.autopairs")
require("nelavim.scnvim")
