#!/bin/bash
# alias scvim="bash $XDG_CONFIG_HOME/zsh/scvim_startup.sh"
alias firefox="open -a Firefox"
alias notion="open -a Notion"
alias chrome="open -a Google\ Chrome"
alias netflix="open -a Firefox 'https://www.netflix.com'"
# alias luamake=/Users/nela/.local/share/lang-servers/lua-language-server/3rd/luamake/luamake
# alias dots="cd ${DOTS}"
alias vimconf="cd ${NVIM} && nvim init.vim"
alias zshconf="cd ${ZSH} && nvim zsh/.zshrc"
alias shell="exec ${SHELL}"
# alias aliasconf="nvim ${DOTS}/scripts/aliases.sh"
alias tat="tmux a -t"
alias tk="tmux kill-ses -t"
alias tl="tmux ls"
alias tn="tmux new -s"
